name: Node.js package

on:
  push:
    branches:
      - master
      - develop

jobs:

  publish-gpr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: '0'
          token: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}

      - uses: actions/setup-node@master
        with:
          node-version: 14

      - name: Bump Version and Push Tag
        id: bump_version
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}
          WITH_V: true
          PRERELEASE_SUFFIX: dev

      - name: Publish
        run: |
          npm install
          node publish.mjs --public
        env:
          version: ${{ steps.bump_version.outputs.new_tag }}
          NPM_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
